# apiVersion: extensions/v1beta1
# kind: Ingress
# metadata:
#   name: fanout-ingress
#   labels:
#     run: couchdb
#     app: bigital-backend
# spec:
#   rules:
#   - http: 
#       paths:
#       - path: /
#         backend:
#           serviceName: nginx
#           servicePort: 80
#       - path: /db
#         backend:
#           serviceName: couchdb
#           servicePort: 5984
#       - path: /backend
#         backend:
#           serviceName: bigital-backend
#           servicePort: 8080


# apiVersion: extensions/v1beta1
# kind: Ingress
# metadata:
#   name: bigital-backend-ingress
#   annotations:
#     kubernetes.io/ingress.global-static-ip-name: bigital-backend
#   labels:
#     app: bigital-backend
# spec:
#   rules:
#   - http:
#       paths:
#       - path: /
#         backend:
#           serviceName: bigital-backend
#           servicePort: 8080

apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: bigital-backend-ingress
  labels:
    app: bigital-backend
spec:
  backend:
    serviceName: bigital-backend
    servicePort: 8080