apiVersion: v1
kind: Service
metadata:
  name: couchdb
  labels:
    run: couchdb
spec:
  ports:
    - name: couchdb
      port: 5984
      targetPort: 5984
      protocol: TCP
  selector:
    run: couchdb
  type: NodePort
